#!/bin/bash

python simulate.py games/beach $@ $(./common.sh ) scrubbing_intent.lp  --project 1 -t 6


python simulate.py games/dinner $@ $(./common.sh ) dinner_intent.lp  --project 1 -t 6

python simulate.py games/lecture_attractMode $@ $(./common.sh ) lecture_intent_attract.lp  --project 1 -t 6
python simulate.py games/lecture_dodgeMode $@ $(./common.sh ) lecture_intent_avoid.lp  --project 1 -t 6
python simulate.py games/lecture_scrubMode $@ $(./common.sh ) lecture_intent_clear.lp  --project 1 -t 6
python simulate.py games/lecture_drawMode $@ $(./common.sh ) lecture_intent_drop.lp  --project 1 -t 6
