#!/bin/bash


python simulate.py games/dinner $@ $(./common.sh ) dinner_intent.lp  --project $@

python simulate.py games/lecture $@ $(./common.sh ) lecture_intent.lp  --project $@

python simulate.py games/travel $@ $(./common.sh ) travel_intent.lp  --project $@

python simulate.py games/dean $@ $(./common.sh ) dean_intent.lp  --project $@

python simulate.py games/beach $@ $(./common.sh ) scrubbing_intent.lp  --project $@
