#!/bin/bash
PYTHON=python3
THREADC=14
MODELC=0

set -e

if [ $# -eq 0 ]
then echo "No arguments given, pass number of games for each intent"
     exit 1
fi

$PYTHON simulate.py games/beach $@ $(./common.sh ) scrubbing_intent.lp  --project $MODELC -t $THREADC

$PYTHON simulate.py games/dinner $@ $(./common.sh ) dinner_intent.lp  --project $MODELC -t $THREADC

$PYTHON simulate.py games/lecture_attractMode $@ $(./common.sh ) lecture_intent_attract.lp  --project $MODELC -t $THREADC
$PYTHON simulate.py games/lecture_dodgeMode $@ $(./common.sh ) lecture_intent_avoid.lp  --project $MODELC -t $THREADC
$PYTHON simulate.py games/lecture_scrubMode $@ $(./common.sh ) lecture_intent_clear.lp  --project $MODELC -t $THREADC
$PYTHON simulate.py games/lecture_drawMode $@ $(./common.sh ) lecture_intent_drop.lp  --project $MODELC -t $THREADC

$PYTHON simulate.py games/dean $@ $(./common.sh ) new_dean_intent.lp  --project $MODELC -t $THREADC

$PYTHON simulate.py games/un $@ $(./common.sh ) new_un_intent.lp  --project $MODELC -t $THREADC
